name: mac-people
favicon: null
layout_spectrum: 0.37590808770619333
typography_spectrum: 0.9560601701959968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.09211375471204519
  lightness: 0.24735245830379426
  saturation: 0.7603362191002816
  rhythmicContrast: 0.5827160961925983
purpose: []
